name: OsirisALPHA
on: [pull_request, push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild Osiris
      working-directory: Osiris
      run: msbuild Osiris.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m
    - name: SHA1 Osiris
      working-directory: Osiris/Release
      run: sha1sum Osiris.dll > Osiris.dll.sha1
    - name: Delete trash files before upload
      working-directory: Osiris/Release
      run: | 
            mkdir dll
            Move-Item -Path D:\a\Osiris\Osiris\Osiris\Release\Osiris.dll -Destination D:\a\Osiris\Osiris\Osiris\Release\dll\Osiris.dll
            Move-Item -Path D:\a\Osiris\Osiris\Osiris\Release\Osiris.dll.sha1 -Destination D:\a\Osiris\Osiris\Osiris\Release\dll\Osiris.dll.sha1
      shell: pwsh
    - uses: actions/upload-artifact@v1
      with:
        name: OsirisALPHA
        path: Osiris/Release/dll
