name: Osiris

on: [pull_request, push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild SSE2
      working-directory: Osiris
      run: msbuild Osiris.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:EnableEnhancedInstructionSet=StreamingSIMDExtensions2 /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\SSE2\"
    - name: Rename SSE2
      working-directory: Osiris/Release/SSE2
      run: ren Osiris.dll Osiris_SSE2.dll
      shell: cmd
    - name: SHA1 SSE2
      working-directory: Osiris/Release/SSE2
      run: sha1sum Osiris_SSE2.dll > Osiris_SSE2.dll.sha1
    - name: MSBuild AVX
      working-directory: Osiris
      run: msbuild Osiris.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:EnableEnhancedInstructionSet=AdvancedVectorExtensions /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\AVX\"
    - name: Rename AVX
      working-directory: Osiris/Release/AVX
      run: ren Osiris.dll Osiris_AVX.dll
      shell: cmd
    - name: SHA1 AVX
      working-directory: Osiris/Release/AVX
      run: sha1sum Osiris_AVX.dll > Osiris_AVX.dll.sha1
    - name: MSBuild AVX2
      working-directory: Osiris
      run: msbuild Osiris.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:EnableEnhancedInstructionSet=AdvancedVectorExtensions2 /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\AVX2\"
    - name: Rename AVX2
      working-directory: Osiris/Release/AVX2
      run: ren Osiris.dll Osiris_AVX2.dll
      shell: cmd
    - name: SHA1 AVX2
      working-directory: Osiris/Release/AVX2
      run: sha1sum Osiris_AVX2.dll > Osiris_AVX2.dll.sha1
    - name: Delete trash files before upload
      working-directory: Osiris/Release
      run: |
            Remove-Item D:\a\Osiris\Osiris\Osiris\Release\SSE2\*.i*
            Remove-Item D:\a\Osiris\Osiris\Osiris\Release\AVX\*.i*
            Remove-Item D:\a\Osiris\Osiris\Osiris\Release\AVX2\*.i*
      shell: pwsh
    - name: Move to one folder
      working-directory: Osiris/Release
      run: |
            mkdir D:\a\Osiris\Osiris\Osiris\Release\All
            Copy-Item -Path D:\a\Osiris\Osiris\Osiris\Release\SSE2\*.* -Destination D:\a\Osiris\Osiris\Osiris\Release\All\
            Copy-Item -Path D:\a\Osiris\Osiris\Osiris\Release\AVX\*.* -Destination D:\a\Osiris\Osiris\Osiris\Release\All\
            Copy-Item -Path D:\a\Osiris\Osiris\Osiris\Release\AVX2\*.* -Destination D:\a\Osiris\Osiris\Osiris\Release\All\
      shell: pwsh
    - uses: actions/upload-artifact@v1
      with:
        name: Release All
        path: Osiris/Release/All
